---
- name: Ansible Variable Example Playbook
  hosts: all
  tasks:


    # display the variable data type
    - debug:
        msg: 
          - " Data type of 'ansible_hostname'  is {{ ansible_hostname | type_debug }} "
          - " Data type of 'ansible_all_ipv4_addresses' is {{ ansible_all_ipv4_addresses | type_debug }} "

    # Simply printing the value of fact
    - debug:
        msg: "{{ ansible_hostname }}   {{ansible_fqdn}}   {{ansible_all_ipv4_addresses[1]}}   ansible_uptime_seconds"
